#
# Makefile for the IEEE 802.1d ethernet bridging layer.
#

obj-${CONFIG_AUTH_REDIRECT} += auth_redirect.o
auth_redirect-y	:= auth_core.o auth_config.o auth_user.o auth_cdev.o auth_checksum.o auth_rule.o http_url_parse.o

